version: "3.7"
services:
  philipposaurus:
    container_name: philipposaurus
    hostname: main_bot
    build: .
    restart: always
    env_file: philipposaurus.env
    depends_on:
      - api
    networks:
      - database
    volumes:
      - ./philipposaurus:/philipposaurus
  api:
    container_name: bridge-api
    hostname: api
    image: bridge-api
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.srv_homepage.loadbalancer.server.port=8000"
      - "traefik.http.routers.r_homepage.rule=Host(`api.poweredbyfluxi.ml`)"
      - "traefik.http.routers.r_homepage.entrypoints=websecure"
      - "traefik.http.routers.r_homepage.tls=true"
      - "traefik.http.routers.r_homepage.tls.certresolver=myresolver"
    networks:
      - database
      - proxy
networks:
  default:
    external:
      name: main
  database:
    external:
      name: database
  proxy:
    external:
      name: proxy